const app=document.querySelector('#app'),robot='assets/robot.webp';
const S={screen:'start',step:0,hall:0,clues:[],open:null,choice:null,plan:null,completed:false};
const clue={ledger:['账本记录','账面资产并不少，但近期可直接支取的现银记录出现断档。'],arrival:['到款核对','几笔应收款尚未按时到账，账面收入与实际到款出现时间差。'],cashier:['账房问询','日常支出集中在近期，现银周转因此变得紧张。']};
const esc=s=>s;
function start(){app.innerHTML='<section class="screen start"><div class="topbar"><h1 class="title">工银金融<br>时空局</h1><p class="subtitle">进入历史，修复失衡的财富系统</p></div><div class="start-cta"><button data-a="launch">启动时空档案　›</button><p class="caption">参赛概念原型</p></div></section>'}
function prologue(){app.innerHTML=`<section class="screen prologue"><div><div class="pulse"></div><h2>${S.step<2?'时空档案已唤醒':'正在检索历史财富系统……'}</h2><p>${S.step<2?'正在验证调查权限……':'检测到异常档案，信号来源未确认'}</p></div><button class="skip" data-a="hall">跳过序章</button></section>`;if(S.step<4)setTimeout(()=>{S.step++;render()},1100);else setTimeout(()=>{S.screen='hall';S.hall=0;render()},700)}
function hall(){const gate=S.hall<2?`<div class="modal-layer"><div class="modal-card"><h2>${S.hall===0?'身份确认':'任务说明'}</h2><p>${S.hall===0?'见习财富调查员':'历史中的财富系统正在失衡，请进入不同世界调查异常原因。'}</p><button data-a="hall-next">${S.hall===0?'确认身份':'继续'}</button></div></div>`:'';const body=`<section class="screen hall ${S.hall<2?'gated':''}"><header class="hall-head"><h1 class="title">管理局大厅</h1><div class="identity"><span class="dot"></span>身份确认　见习财富调查员</div></header><div class="archive-list"><article class="archive primary"><h2>贾府现金流危机</h2><p class="alert">现金流异常</p><p>账面资产充裕，可用现银持续减少</p><button data-a="case">查看贾府档案　›</button></article><article class="archive muted"><h2>鲁滨逊岛资本实验</h2><p>档案封存</p></article><article class="archive muted"><h2>百万英镑信用迷局</h2><p>待解锁</p></article></div><div class="assistant"><img src="${robot}" alt="工小智"><p>检测到贾府档案异常。<br>账面资产充裕，可用现银却持续减少。</p></div></section>`;app.innerHTML=body+gate}
function caseBrief(){app.innerHTML='<section class="screen hall"><div class="modal-layer"><div class="modal-card"><h2>贾府现金流危机</h2><p>任务：找出缺钱的原因<br>目标：恢复贾府短期支付能力</p><button data-a="jiafu">进入贾府</button></div></div></section>'}
function jiafu(){const ids=['ledger','arrival','cashier'],names=['查看账本','核对到款','询问账房'];let buttons=ids.map((id,i)=>`<button class="hotspot ${['one','two','three'][i]} ${S.clues.includes(id)?'seen':''}" data-a="clue" data-id="${id}">${names[i]}${S.clues.includes(id)?'　✓':''}</button>`).join('');let detail=S.open?`<div class="clue-panel"><h3>${clue[S.open][0]}</h3><p>${clue[S.open][1]}</p><button data-a="close-clue">返回账房</button></div>`:'';let decision=S.clues.length===3&&!S.open?(S.choice?`<div class="decision-panel"><h3>判断已记录</h3><p>你选择：${S.choice}</p><p>核心问题是资金到账与支出发生的时间错配。</p><button data-a="act2">进入下一幕</button></div>`:`<div class="decision-panel"><h3>线索已齐</h3><p>请选择你判断的主要原因</p><div class="decision-options"><button data-a="choose">资产不足</button><button data-a="choose">收入不足</button><button data-a="choose">收支时间错配</button><button data-a="choose">日常支出过高</button></div></div>`):'';app.innerHTML=`<section class="screen paper-screen"><header class="paper-head"><h1>贾府现金流危机</h1><p>第一幕 · 查清账目</p></header><div class="case-strip"><strong>现银待核对</strong><span>任务：找出缺钱的原因</span></div><div class="room-actions">${buttons}</div><div class="dialogue"><h3>账房先生</h3><img class="robot" src="${robot}" alt="工小智"><p>府里家底不少，<br>可眼下能用的现银不多。</p></div><div class="case-cta"><button class="primary">开始查账　›</button></div>${detail}${decision}</section>`}
function act2(){let content=S.plan?`<h2>阶段结果</h2><p>现银压力暂时缓解，但仍需持续核对收入与支出的时间安排。</p><div class="result-metric"><span>短期支付能力</span><strong>+1</strong></div><div class="result-metric"><span>资金周转风险</span><strong>下降</strong></div><button data-a="review">进入复盘</button>`:S.choice?`<h2>安排已提交</h2><p>已选择：${S.choice}。账房将据此调整近期周转。</p><button data-a="result">查看阶段结果</button>`:'<h2>调整周转</h2><p>账房只能优先处理一项，请结合线索作出决定。</p><button data-a="plan" data-plan="优先催收应收款">优先催收应收款</button><button data-a="plan" data-plan="延后非必要支出">延后非必要支出</button>';app.innerHTML=`<section class="screen paper-screen act2"><header class="paper-head"><h1>贾府现金流危机</h1><p>第二幕 · 调整周转</p></header><div class="case-strip"><strong>现银紧张</strong><span>账面有资产，眼下缺少可用现银</span></div><div class="act2-card">${content}</div><div class="dialogue compact"><h3>工小智</h3><img class="robot" src="${robot}" alt="工小智"><p>先解决时间差，才能让账面资产重新变得可用。</p></div></section>`}
function review(){app.innerHTML='<section class="screen paper-screen"><header class="paper-head"><h1>阶段复盘</h1><p>账面资产与可用现银</p></header><div class="act2-card"><h2>本阶段金融逻辑</h2><p>账面资产充足，不代表当下拥有足够的可用现银。应收款到账与支出发生之间的时间差，会形成现金流压力。</p><button data-a="back-hall">返回管理局</button></div></section>'}
function render(){if(S.screen==='start')start();else if(S.screen==='prologue')prologue();else if(S.screen==='hall')hall();else if(S.screen==='case')caseBrief();else if(S.screen==='jiafu')jiafu();else if(S.screen==='act2')act2();else review()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-a]');if(!b)return;const a=b.dataset.a;if(a==='launch'){S.screen='prologue';S.step=0}else if(a==='hall'){S.screen='hall';S.hall=0}else if(a==='hall-next')S.hall++;else if(a==='case')S.screen='case';else if(a==='jiafu')S.screen='jiafu';else if(a==='clue'){if(!S.clues.includes(b.dataset.id))S.clues.push(b.dataset.id);S.open=b.dataset.id}else if(a==='close-clue')S.open=null;else if(a==='choose')S.choice=b.textContent.trim();else if(a==='act2')S.screen='act2';else if(a==='plan'){S.plan=b.dataset.plan;S.choice=S.plan}else if(a==='result')S.plan=S.choice;else if(a==='review')S.screen='review';else if(a==='back-hall'){S.completed=true;S.screen='hall';S.hall=2}render()});render();
document.addEventListener('click',e=>{if(!e.target.closest('[data-a="result"]'))return;setTimeout(()=>{const card=document.querySelector('.act2-card');if(!card)return;const text={"资产不足":"资产处置带来少量现银，但长期资产结构仍需调整。","收入不足":"收入端得到补充，但回款周期仍然较长。","收支时间错配":"催收与延后支出同时缓解了短期周转压力。","日常支出过高":"支出压力下降，但应收款到账问题仍未解决。"}[S.choice]||'';const p=card.querySelector('p');if(p&&text)p.textContent=text},0)});
